### ISSUE TITLE
Limitless breaks Gson?

### ISSUE THREAD

**Issue by thexaero** [user11681/limitless#44]
Having Limitless installed on 1.17 seems to break the Gson library. This causes my minimap mod to crash.
Crash report:
[https://pastebin.com/eMKv5N8a](https://pastebin.com/eMKv5N8a)
Is it something you could fix on your end?
Thank you for your time!

**Comment by user11681** [comment]
Fixed in version 1.3.2. Hopefully this is the last reflection-related issue.

**Comment by thexaero** [comment]
Thank you very much for the quick fix!
If it's not too much to explain, can you please tell me what the issue was?

**Comment by user11681** [comment]
My little reflection library cleared the reflection field filter map. (I never had a use for that but still added it. :man_shrugging:) When Gson tried to make a reflective type adapter for a `Method` field in `EntityIconDefinition` during deserialization, it iterated over the fields returned by `Class<Method>#getDeclaredFields` and attempted to make them accessible. Ordinarily no field is returned; but with an empty field filter map, every field is returned. That resulted in an exception because the fields are not opened to the unnamed module.

**Comment by thexaero** [comment]
I see, thank you. I was pretty confused by the way you fixed the issue, so this definitely clears things up. Not sure why Gson needs to touch fields in `EntityIconDefinition` that aren't included in the JSON string but it's good to know. Going to make use of the `@Expose` annotation to only include necessary fields in deserialization. Seems like a good idea all around.

**Comment by user11681** [comment]
Gson also excludes `transient` and `static` fields by default, which might save you some effort.

**Comment by thexaero** [comment]
Yeah, I know, but there is only 4 fields to expose, which is exactly half of the fields. I think there might be more excluded fields added soon, so it just feels more intuitive to include rather than exclude. I might forget to exclude a new field and not notice it but forgetting to include a field will be hard to miss because it will actually break things.
